name: Complex Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: bmx-runner
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!


